name: liquid_toggle_bar
description: Horizontal tab interface capable of handing any number of inputs.  Easily customize colors with an easy to use set of attributes.
version: 0.4.0
homepage: https://liquidsoft.io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


